#!/bin/sh

H=helloworld

mkdir -p ${H}/DEBIAN
mkdir -p ${H}/usr/local/bin
cp hello.sh ${H}/usr/local/bin/

cat<<EOF>${H}/DEBIAN/control
Package: helloworld
Version: 0.1
Maintainer: Wojciech Adam Koszek <wojciech@koszek.com>
Architecture: all
Description: nothing special. just a hello world program
EOF

cat<<EOF>${H}/DEBIAN/postinst
echo "post install script!"
EOF
chmod 0755 ${H}/DEBIAN/postinst

dpkg-deb --build ${H}
echo "built!"
